name: Build and Publish to PyPI
on: push

jobs:
  build-n-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
    - name: Get closest tag
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
    - name: Get next minor version
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v1
      with:
        python-version: 3.10
    - name: Install requirements
      run: >-
        python -m
        pip install
        build wheel
        --user
    - name: run unit tests
      run: python -m pytest
    - name: Build release module
      if: startsWith(github.ref, 'refs/tags')
      run: python setup.py egg_info sdist bdist_wheel
    - name: Publish to PyPI
      if: startsWith(github.ref, 'refs/tags')
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
    - name: Build snapshot
      if: github.ref == 'refs/heads/main'
      run: SETUPTOOLS_SCM_PRETEND_VERSION="${{steps.semvers.outputs.patch}}.${GITHUB_RUN_NUMBER}" python setup.py sdist bdist_wheel
    - name: Publish to Test PyPI
      if: github.ref == 'refs/heads/main'
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
